openapi: 3.0.1
info:
  title: 'My API'
  version: 1.0.0
paths:
  '/pets':
    get:
      operationId: getPets
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
  '/pets/{id}':
    get:
      operationId: getPetById
      responses:
        '200':
          description: ok
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    responses:
      '200':
        description: ok
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string      